### ISSUE TITLE
install script does rm -rf /usr for ubuntu

### ISSUE THREAD

**Issue by ginoputrino** [MrMEEE/bumblebee-Old-and-abbandoned#123]
An extra space at line 351:
rm -rf /usr /lib/nvidia-current/xorg/xorg

causes the install.sh script to do an rm -rf  on the /usr directory for people installing in ubuntu.

Totally uncool dude!!! The script deletes everything under /usr. I just had to reinstall linux on my pc to recover.

Removing the space will fix this. Probably should do it quickly!!!

**Comment by 1and1get2** [comment]
Haha people even reference to this issue lolol

Long it will be remembered

**Comment by turshija** [comment]
Link to a commit for future reference, awesomeness and epic comments since this issue comes up in Google instead:

https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6#diff-1

**Comment by ayr-ton** [comment]
![](http://www.planetcalypsoforum.com/gallery/files/4/5/5/0/8/mother-god-meme.jpg)

**Comment by sximaget** [comment]
LOL, i am on the process of [recovering](http://www.iphonetransferrecovery.com/tutorials/recover-iphone-contacts-mac.html) my own files.  Fortunately, it's just a test machine. I'd love to see if some one deployed the script on an working server

**Comment by JarJak** [comment]
mom i have been here

**Comment by tishion** [comment]
So interesting a bug

**Comment by Serkan-devel** [comment]
Just place the space before <code>usr</code>.<br>
Example:<code># rm -rf / usr/...</code><br>
It anyway doesn't come with any warranty so..

**Comment by Wampirue** [comment]
Oh boy. This really exists.

**Comment by rayfoss** [comment]
![south-park-cable-company-comcast-oh-jeez-were-so-sorry](https://user-images.githubusercontent.com/876076/27249435-152ab5bc-52db-11e7-957e-fb7044b1705b.jpg)
I find my self coming back to this commit for laughs, so this.

**Comment by chewenkai** [comment]
I just heard about this and come around to see what happened, and…hahaha…

**Comment by HIMix** [comment]
We still remember!

**Comment by ycjcl868** [comment]
nice~

**Comment by zhanchengqian** [comment]
wow

**Comment by jofftiquez** [comment]
WAHAHAHAHAHAHA

**Comment by ice1000** [comment]
Leave my name here so that subsequent viewers will see my name :joy:

**Comment by jofftiquez** [comment]
@ice1000 same here haha

**Comment by Marcerisson** [comment]
Same for me x) My IT teacher show me this one

**Comment by DevChache** [comment]
Tourists from [Zhihu.com](https://www.zhihu.com/question/62248491/answer/196307179)

**Comment by Zainking** [comment]
Tourists from Zhihu.com + 1
23333333333333333333333333333

**Comment by XAS-712** [comment]
“This is a visitor from ![Zhihu](www.zhihu.com).”

**Comment by mzhang28** [comment]
like this if ur reading in 2007

**Comment by 0kaguya** [comment]
how could this happen...

**Comment by azarovalex** [comment]
I'm writing in the epic thread.

**Comment by jofftiquez** [comment]
Hi from May, 2018

**Comment by Erkin97-zz** [comment]
Hi from June, 2018. We are in the history of github forever

**Comment by tobytteh** [comment]
🤪

**Comment by krdecker** [comment]
Like exploring abandoned subway tunnels. *distant echoes*

*scrabbling rats*

**Comment by Serkan-devel** [comment]
I wish one can just, reverse the acquisition from Microsoft

**Comment by jofftiquez** [comment]
@Serkan-devel will you fund github's dying business model then?

**Comment by Yodzorah** [comment]
What a nice place for meditation.

**Comment by blueabysm** [comment]
It happened in the first year of my career as a programmer, still remember it!

**Comment by jofftiquez** [comment]
Hello from Aug, 2018!

**Comment by Li-Aaron** [comment]
It's really famous. :)

**Comment by cbeuw** [comment]
https://www.theregister.co.uk/2018/10/05/windows_10_wipes_files/

Microsoft you may want to check for extra spaces...

**Comment by jofftiquez** [comment]
Hello from October, 2018

**Comment by Yodzorah** [comment]
Stop this "hello from <date>" stupid bullshit, please. It's October, 2018, and you still don't understand what happens to a joke spoken twice.

**Comment by jofftiquez** [comment]
@Yodzorah It's not a joke. It's a greeting. Learn the difference. Hello from October 2018! 🤣 ☮️

**Comment by minhng99** [comment]
Microsoft just has done something like this with Oct 2018 update...

**Comment by Serkan-devel** [comment]
At least we know where MrMEEE now works

**Comment by HPaulowicz** [comment]
@jofftiquez Hello from November, 2018 🤣

**Comment by jofftiquez** [comment]
@HPaulowicz hey mate! Hello from November, 2018! 🤣

**Comment by ascii766164696D** [comment]
oh 💞🌻🦋🍃oh shit 💚 🦋 🍃 💛 🌷 ✨🍂 💘shit💞🌼 💞✨💛🦋sorry guys🌻🍄 💖 🌻💞im sending my hi from 2019 to💗 ✨all of you 🌼 🦋 💘🍃 💘🌷 💞 🦋 ✨ 🌷 🍃🦋 all over the 💚🍂🌻✨ 🌷 💘🌼🍂🦋✨ 💗place🍄🌻 🌺 💞🦋🌷 sorry 💘🌼

**Comment by jofftiquez** [comment]
@Yodzorah Hello from May 2019.

**Comment by aviranzerioniac** [comment]
This is probably why, we are repeatedly told to check everything. Thanks, for setting a perfect example.

**Comment by ysfduzgun** [comment]
Mustafa Akgül Özgür Yazılım Yaz Kampı 2019

**Comment by aiv** [comment]
Hello from 11/2019 :)

**Comment by jofftiquez** [comment]
@aiv hello too! November 2019!

**Comment by lkocman** [comment]
Where is the history?!!!! :-)

**Comment by ghost** [comment]
This issue will end in History books

**Comment by zhuangat** [comment]
Dude, it's 2020 now, long may the bumblebee

**Comment by Sharcoux** [comment]
For further references:
- The [commit introducing](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/6cd6b2485668e8a87485cb34ca8a0a937e73f16d) the bug (19 comments)
- The [commit removing](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac) the bug (1011 comments), that I could access only throught the [wayback machine](https://web.archive.org/web/20191015125002/https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac) or [webcache](http://webcache.googleusercontent.com/search?q=cache:https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac)

I like to check it sometimes. Even 9 years later it is still funny ^ ^

**Comment by leetfin** [comment]
Well, another issue happened that's leading people back to this thread. [The Minecraft Dungeons launcher is deleting files.](https://bugs.mojang.com/browse/MCL-14107)

**Comment by async3619** [comment]
now, eventually this issue had faded out from peoples head. and I'm very bored now. can someone follow me please?

**Comment by async3619** [comment]
now, eventually this issue had faded out from peoples head and I've read all the github-drama issues. someone can suggest me a good funny github issues or PRs? (FYI, I think a issue of `flatmap-stream` package is best thing ever I've read)

and I would like to be happy when you follow me too 😘
![](https://i.imgur.com/83wS2X4.png)

**Comment by waluigispear2** [comment]
[What these issue comments remind me of](https://xkcd.com/1305/)

**Comment by ideas-man** [comment]
So, it is true. Amazing...

![image](https://user-images.githubusercontent.com/60187905/96633558-916ecd00-1319-11eb-924a-5aa39318d460.png)

**Comment by ghost** [comment]
Almost 2021 and we are still here!

**Comment by Arawasu** [comment]
posting in epic thread

**Comment by parasetam0l** [comment]
This topic comes to my mind when I make a typo in my code.

**Comment by ImSkully** [comment]
Hello from 2021 (:

**Comment by jofftiquez** [comment]
This issue will be 10 years old in May 24 this year. Congrats to you all legends. Our names will go down in history. HAHAHAHA

**Comment by m2kulkarni** [comment]
How did i land up here

**Comment by xiaoxi-ij478** [comment]
celebrate its 10 years old birthday on 2021-5-24

**Comment by alakdae** [comment]
That must have been painful ;]

**Comment by dima2306** [comment]
Haha LOL https://restyled.io/ brought me here 😂

**Comment by ghost** [comment]
> An extra space at line 351:
> rm -rf /usr /lib/nvidia-current/xorg/xorg
> 
> causes the install.sh script to do an rm -rf on the /usr directory for people installing in ubuntu.
> 
> Totally uncool dude!!! The script deletes everything under /usr. I just had to reinstall linux on my pc to recover.
> 
> Removing the space will fix this. Probably should do it quickly!!!

OH GOD

**Comment by Itzbenz** [comment]
lol

**Comment by heyitsarpit** [comment]
Hi guys!!!

**Comment by Jerome226** [comment]
it is old

**Comment by TranNgocKhoa** [comment]
Hello from 2021

**Comment by Duvio** [comment]
Reddit brought me here

Hello

**Comment by xeon3175x** [comment]
Shut up redditors

**Comment by agent255** [comment]
Dont dislike pls i am cool boi

**Comment by CypherpunkSamurai** [comment]
Wow this issue has become a github chat. People really like talking about it.

Merch coming soon? 😆

**Comment by aarav2you** [comment]
please dislike my post

**Comment by dyanakiev** [comment]
🤣

**Comment by dmitrijkiltau** [comment]
lol

**Comment by FranLMSP** [comment]
lmao I used to use Bumblebee, I didn't know any of this

**Comment by OBITORASU** [comment]
Reddit brought me here

**Comment by scardena** [comment]
Programming Memes for Object-oriented Teens brought me here

**Comment by jonjefemet** [comment]
No man, esas cosas si están bien turbias XD

**Comment by jLincopan** [comment]
Bien turbio, vengo desde el 2021 y esto se ha vuelto una especie de meme! jajajaj

**Comment by RedShift1** [comment]
![image](https://user-images.githubusercontent.com/3098010/109198784-ea0a1700-779e-11eb-9071-26c300ef33b7.png)

**Comment by GiaHuynh** [comment]
All comments under this one is ghaey

**Comment by bzbug** [comment]
> All comments under this one is ghaey

° ͜ʖ ͡ -

**Comment by DannyAndres** [comment]
This will be remembered for years
![dont-care](https://user-images.githubusercontent.com/19177489/109224284-8251cd00-779a-11eb-88af-44d725c544cb.png)

**Comment by apes0** [comment]
:)

**Comment by naverlyn** [comment]
F

**Comment by Hamza417** [comment]
Not trying to bother or anything but is the issue fixed yet ?

**Comment by isfaaghyth** [comment]
LOL :)))

**Comment by isfaaghyth** [comment]
:))))

**Comment by geekswamp** [comment]
Hallo!

**Comment by qaisjp** [comment]
lmao

**Comment by WilliamColmenares** [comment]
LOL

**Comment by ghost** [comment]
What are we doing on its 10 year anniversary?

**Comment by RedShift1** [comment]
> What are we doing on its 10 year anniversary?

Unsubscribing from this thread

**Comment by SilverCory** [comment]
oof

**Comment by varlesh** [comment]
I like this bug!!!

**Comment by kazani-dev** [comment]
Oh no.... also why is there so much chatting on this thread...

**Comment by SollyW** [comment]
:eyes:

**Comment by ghost** [comment]
> Oh no.... also why is there so much chatting on this thread...

Because it is an epic thread and our grand kids will remember it.

**Comment by PogromistDev** [comment]
🤣🤣🤣

**Comment by sxd** [comment]
Best issue ever!!

**Comment by aaravrav** [comment]
petition to close this thread, dislike if agree. like if agree. all emojis if agree

**Comment by umutphp** [comment]
This bug deserves to be in the [Famous Bugs](https://github.com/umutphp/famous-bugs#the-forgotten-space-character) list :)

**Comment by QWERTY770** [comment]
👍

**Comment by TheSecondDiaryKeeper** [comment]
https://user-images.githubusercontent.com/71950082/111694923-ba738b00-87ef-11eb-8bb3-ec453ba0993d.mp4

**Comment by AdamZaczek** [comment]
Github was made so this bug report could happen

**Comment by lazaroblanc** [comment]
Hi Mom!

**Comment by code913** [comment]
This is the most reposted thing on r/ProgrammerHumor pls stahp

**Comment by ghost** [comment]
I'm surprised this hasn't been locked yet.

**Comment by RedStone576** [comment]
still funny

**Comment by rayalex** [comment]
F

(for posterity)

**Comment by Woolworths** [comment]
F

**Comment by kkl4261** [comment]
F. This shall be remembered until the end of Internet.

**Comment by Aliics** [comment]
F

**Comment by dullbananas** [comment]
LiNuX dOeSn'T HaVe maLwaRE

**Comment by code913** [comment]
tbf linux doesnt have github desktop :(

**Comment by bayasdev** [comment]
F

**Comment by ghost** [comment]
> tbf linux doesnt have github desktop :(

What?
https://aur.archlinux.org/packages/github-desktop-bin/

**Comment by code913** [comment]
:shushing_face:

**Comment by ZorudaRinku** [comment]
HAPPY 10 YEAR ANNIVERSARY! 🎉

**Comment by anka-213** [comment]
Happy Anniversary! 🥳 🎊🚀 🎆

**Comment by lucamotion** [comment]
🎉 🎉 🎉

**Comment by tgrekov-mhl** [comment]
Happy 10 year hell

**Comment by RafKulas** [comment]
Happy 10th Anniversary! 🎉 🎉 🎉

**Comment by Chriserus** [comment]
10 years!

**Comment by Niedzwiedzw** [comment]
F

**Comment by Tsubajashi** [comment]
Happy Anniversary!

**Comment by Magenta-Puppy** [comment]
Happy anniversary, rm bug!

**Comment by gwennlbh** [comment]
Happy 10 years!

**Comment by ViktorBash** [comment]
Fun times

**Comment by nathanfranke** [comment]
Still reproducible

**Comment by brycedewitt** [comment]
lgtm

**Comment by donno2048** [comment]
Makes sense LOL

**Comment by simonwuelker** [comment]
I'm a little late to the party but happy anniversary!

**Comment by somnisomni** [comment]
Such a legend...😂

**Comment by loquesangra** [comment]
Never forget.

**Comment by syo093c** [comment]
神话留名

**Comment by syo093c** [comment]
神话留名

**Comment by bshankya93** [comment]
G(old)

**Comment by MFWT** [comment]
火钳刘明...啊是火后刘明

**Comment by etkaar** [comment]
Happy New Year!

**Comment by Insik-Won** [comment]
leave a flower for who removed their files

**Comment by ni5arga** [comment]
This is interesting!!

**Comment by orhun** [comment]
“Life's but a walking shadow, a poor player,
That struts and frets his hour upon the stage,
And then is heard no more. It is a tale
Told by an idiot, full of sound and fury,
Signifying nothing.” 
― William Shakespeare, Macbeth

**Comment by raunak51299** [comment]
This is funny.

**Comment by Sakimotor** [comment]
Absolute legend

**Comment by ghost** [comment]
i love that people are still commenting on this

**Comment by xcenai** [comment]
im here !!

**Comment by RelatedTitle** [comment]
0_0

**Comment by etkaar** [comment]
> Don't think life plain sailing;
There's danger of failing,
Though bright seem the future to be;
But honor and labor,
And truth to your neighbor,
Will bear you safe over life's sea.

From «Be Honest And True», George Birdseye, Golden Days for Boys and Girls, 1887

**Comment by QuanTrieuPCYT** [comment]
lollll

**Comment by ghost** [comment]
People using Ubuntu deserve this, lol.

**Comment by AdamZaczek** [comment]
I get sentimental every time I think about this issue

**Comment by TheGamer1002** [comment]
Even more than 10 years after somebody's computer broke with a simple typo, there are still comments on the relevant issue.

**Comment by grepsedawk** [comment]
I love that the most recent comment was ~~23~~ 0 days ago

**Comment by snuggs** [comment]
*ping* Any idea when this will land?

+1

**Comment by t3dium** [comment]
what a legend lmfao

**Comment by ghost** [comment]
this is the power of linux

**Comment by fourteentrees** [comment]
give this man a round of applause. his styling caused linux to commit die

**Comment by newyorkin** [comment]
just touch history

**Comment by jofftiquez** [comment]
Hello from May, 2022 🎊

**Comment by Mitgenosse** [comment]
Happy anniversary, y'all! :tada:

**Comment by fihovi** [comment]
Happy 11th anniversary!  🎉

**Comment by Cyanic76** [comment]
> just touch history

GitHub history

**Comment by itsHanibee** [comment]
hello hello whoever is still here <3 i hope you're all doing okay. always keep that brilliant smile of yours and its been a little too long since you've drank some water, it would be nice if you got some. its good for you ^^

remember that you're loved and see you all in a few years once again-

**Comment by Cyanic76** [comment]
Hi from June 2022.

**Comment by the-eduardo** [comment]
```
Hello darkness, my old friend
I've come to talk with you again
Because a vision softly creeping
Left its seeds while I was sleeping
And the vision that was planted in my brain
Still remains
Within the sound of silence
```

**Comment by MrCroxx** [comment]
No offense, but when I feel down on my life, I will come back to see what happened in history to refresh my day.

**Comment by keethesh** [comment]
How to build the Nether Portal like Dream in Minecraft?

**Comment by bzbug** [comment]
How to patch KDE under FreeBSD?

**Comment by NewCentury99** [comment]
Wow..!
If the typo was "/ usr/blahblah"

Then.. it will delete root directory with all hard drives and even if mainboard EFI bios.. isn't it..?

(Of course, latest versions of major linux distribution has --no-preserve-root switch and /efi is default mounted at Read-Only, but if you are using minor distribution or legacy system that doesn't have any "SAFETY"s like that... then......

Whats a horor..

Let's get into the habit of regular backup. lol..!

**Comment by ShashankVenkatramani** [comment]
Historic moment in coding history

**Comment by JustLap** [comment]
Well, looks like thread is still alive

**Comment by Starwort** [comment]
First comment in this thread of 2023

**Comment by EtsuNDmA** [comment]
Congratulate me! Today I've done almost the same thing but using ansible playbooks 🥳

**Comment by AdamZaczek** [comment]
I don't like sand.

**Comment by ShashankVenkatramani** [comment]
ZETTABYTES WAS HERE

**Comment by duncan-bayne** [comment]
I think the real reason I'm so afraid of writing a bug like this myself is that it would stand a good chance of becoming my most-remembered contribution to the field :sob:

**Comment by runarcn** [comment]
ok this is actually pretty fun

**Comment by IverCoder** [comment]
Oh my god.

**Comment by CozyMeli-gitv2** [comment]
hillarious

**Comment by Beryesa** [comment]
"ginoputrino opened this issue on May 24, 2011"
Latest comment: 2 hours ago 

Epic

**Comment by t3dium** [comment]
lol

**Comment by gabriele2000** [comment]
Reddit brought me here.
BTW fuck the time-change (the power-saving hours stuff)

**Comment by jsrobson10** [comment]
discord brought me here lmao

**Comment by Ushie** [comment]
> hello hello whoever is still here <3 i hope you're all doing okay. always keep that brilliant smile of yours and its been a little too long since you've drank some water, it would be nice if you got some. its good for you ^^
> 
> remember that you're loved and see you all in a few years once again-

Hanhan is this you??

**Comment by nostrus-dominion** [comment]
Saw this on a reddit post. Hilarious mistake.

**Comment by AlexHulyi** [comment]
12 years🥳
We still remember

**Comment by FossPrime** [comment]
https://nodejs.org/api/permissions.html#file-system-permissions

Accidental deletions are still a thing... Having some protection from it is still an experimental feature. Despite this being 12 years old. We still have people running `rm -rf ./data` without checking pwd. Is this the best we can do?

I don't like to complain without proposing solutions... So:

How about a standardized tool name written in all languages, that keeps track of your apps files in a YAML file (less verbose, smaller than JSON). And when you need to delete or create, you use it.it will check file name and if tmp is in the same drive, dump all deletions in /tmp. Let's call it the Bumblebee Raft Function, or BRF Spec for short.

**Comment by jayantchandra** [comment]
never not funny

**Comment by ImAvafe** [comment]
💀💀💀

**Comment by Ultra980** [comment]
most iconic mistake in coding

**Comment by jiangyin14** [comment]
We still remember😆
my friend brought me here

**Comment by mkalitka** [comment]
One of the best things I've seen on GitHub for real

**Comment by MoeField** [comment]
乐死了

**Comment by MrKelpy** [comment]
would be a shame if this was installed in /root

**Comment by Ultra980** [comment]
kinda funny that this was issue #123

**Comment by JumperOnJava** [comment]
rip your files

**Comment by balt-dev** [comment]
iconic

**Comment by inimitable** [comment]
Coming to pay my respects to an old favorite. Love this.

**Comment by 1-bytes** [comment]
hahaha, it's now 2023, and people will forever remember this epic bug...

--From China

**Comment by hexqueller** [comment]
hahaha, it's now 2023, and people will forever remember this epic bug...

--From Russia

**Comment by eddyariki** [comment]
hahaha, it's now 2023, and people will forever remember this epic bug...

--From Japan

**Comment by ladyhoai** [comment]
hahaha, it's now 2023, and people will forever remember this epic bug...

--From Australia

**Comment by Undercoverdog** [comment]
Shit Happens
Hope you and your Ubuntu have mentally recovered after 13 years.

hahaha, it's now ~~2023~~ 2024, and people will forever remember this epic bug...

--From Germany

**Comment by a-catgirl-dev** [comment]
hahaha, it's now ~~2023~~ **2024**, and people will forever remember this epic bug...

--From Canada

**Comment by e2ne0** [comment]
hahaha, it's now ~~2023~~ **2024**, and people will forever remember this epic bug...

--From Taiwan

**Comment by lucasrdrgs** [comment]
lmao

**Comment by stepan323446** [comment]
hahaha, it's now 2024, and people will forever remember this epic bug...

--From Serbia

**Comment by wthrajat** [comment]
hahaha, it's now 2024, and people will forever remember this epic bug...

--From India

**Comment by GabrielRavier** [comment]
hahaha, it's now 2024, and people will forever remember this epic bug...

--From France

**Comment by CoolPlayLin** [comment]
lol, it's now January 28th 2024, and people will forever remember this epic bug...

--From China

**Comment by papandadj** [comment]
我知道的有点早了,早知道留春晚看了(⁠づ⁠｡⁠◕⁠‿⁠‿⁠◕⁠｡⁠)⁠づ

**Comment by FeatherXavier** [comment]
omg i'm gonna star this
and surely i just know that rm supports multiple args(

**Comment by FlysoftBeta** [comment]
lmao😂

**Comment by rong-xiaoli** [comment]
lmfao 🤣

**Comment by Moruozhong** [comment]
哈哈，现在是 2024 年 1 月 29 日，人们将永远记住这个史诗般的错误......

--来自中国

**Comment by Moruozhong** [comment]
lol, it's now January 29th 2024, and people will forever remember this epic bug...

--From China

**Comment by DuckyProject** [comment]
hahaha, it's now 2024, and people will forever remember this epic bug...

--From China

**Comment by CoolPlayLin** [comment]
A bug that people would never forget

**Comment by kongtaoxing** [comment]
lol🤣

**Comment by Herminos** [comment]
LOL

**Comment by zeturn** [comment]
打卡经典Bug

**Comment by jhqwqmc** [comment]
打卡

**Comment by ltzXiaoYanMo** [comment]
the bug is too careless, haha

**Comment by ltzXiaoYanMo** [comment]
![Image_1706586948919](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/assets/115706851/c7bf8ea2-9487-4c02-ac38-268d02d366ff)

**Comment by zackzheng1121** [comment]
台灣人打卡，看了小劉不是程序員來這的+1

**Comment by Just-theasdg** [comment]
> 只需将空格放在 .示例：无论如何，它没有任何保修，所以..`usr``# rm -rf / usr/...`

现在是2024年了，打卡一下

**Comment by FlashAndromeda** [comment]
lmao never change please

**Comment by Evil0ctal** [comment]
Let's sudo👍🏻👍🏻👍🏻

**Comment by WilliamJiH** [comment]
Lmao

**Comment by dc10Mayday** [comment]
多敲一个空格，被全球程序员笑了十年

**Comment by daleclack** [comment]
Hello，I am from 2024

**Comment by CloudSVC** [comment]
小问题，至少不是 rm -rf /(space) usr/

**Comment by chengnan049** [comment]
Today is chinese new year and people will forever remember this epic bug...

--From China

**Comment by Buer-Nahida** [comment]
`rm -rf /usr` ` ` `/lib/nvidia-current/xorg/xorg`
That's soo cool. (hahaha)

**Comment by thebigbone** [comment]
hilarious

**Comment by EmK530** [comment]
hello from sweden this bug is funny

**Comment by TGJek** [comment]
LOL

**Comment by Kineforce** [comment]
xDDDDDD

**Comment by Kianda** [comment]
Old but gold!! 🚀

**Comment by starmax2006** [comment]
LOL

**Comment by b1ek** [comment]
i really like issues like that, totally brightens up my day

**Comment by Kyllingene** [comment]
Should this be locked? It's 13 years old, yet people are still responding.

**Comment by b1ek** [comment]
> Should this be locked?

probably

> 13 years old

its insane how there are fortnite players younger than this issue

**Comment by ivanp7** [comment]
> Should this be locked? It's 13 years old, yet people are still responding.

No, never. This thread survived so long, no one has the right to kill it.

**Comment by jiangyin14** [comment]
no. it's a legend

**Comment by catboybinary** [comment]
i was here

**Comment by rpanabfrE** [comment]
Legendary Programmers' Collective Creation

**Comment by fatihaziz** [comment]
Is the most epic accidental programming war crime LMAO

**Comment by duncan-bayne** [comment]
> its insane how there are fortnite players younger than this issue

All of my children are younger than this issue.  One is getting into programming; I'm actually going to show him this as a teaching opportunity.

**Comment by tskxz** [comment]
legend

**Comment by osvetlik** [comment]
Someone just copied your famous marketing campaign :-D

https://www.forbes.com/sites/kateoflahertyuk/2024/07/19/crowdstrike-windows-outage-what-happened-and-what-to-do-next/

**Comment by BlazeInferno64** [comment]
Yo I have been here :)

**Comment by lyricalpaws** [comment]
Put me in the screenshot

**Comment by duncan-bayne** [comment]
I wonder how many times this issue has been shared around amongst Crowdstrike devs :speak_no_evil:

**Comment by HDK101** [comment]
Issue lendaria

**Comment by osbm** [comment]
I was here.

**Comment by TheGuyDangerous** [comment]
I was here 😂

**Comment by nikoumba** [comment]
I've done that with `sudo rm -rf /etc /temp`  🫂
I still remember the command, the cursor that stopped blinking and me noticing the space.
Linux is the ultimate ninja OS, you command it to die and it justs dies, no questions asked. 🥷

**Comment by ncor** [comment]
hello from /g/

**Comment by gmatht** [comment]
> rm -rf / usr/...

Thanks for your workaround, but I am having a little trouble getting it to work
```
xubuntu@xubuntu:-$ rm -rf / usr/lib/nvidia-current/xorg/xorg
rm: it is dangerous to operate recursively on '/'
rm: use --no-preserve-root to override this failsafe
xubuntu@xubuntu:-$ sudo rm -rf / usr/lib/nvidia-current/xorg/xorg
rm: it is dangerous to operate recursively on '/'
rm: use --no-preserve-root to override this failsafe 
```
Could you advise me on the next step? :P

**Comment by prkprime** [comment]
hello there

**Comment by im-hanzou** [comment]
LMAO

**Comment by Aybee5** [comment]
I immediately installed `safe-rm` when I saw this.

**Comment by JackChen890311** [comment]
LOL I just need to leave a comment here, this is epic hahaha

**Comment by rmitache-ai** [comment]
lgtm

**Comment by khangdao2112** [comment]
This is really something xD

**Comment by Godnessy** [comment]
Do I comment here to download a job in FAANG?

**Comment by SSean08** [comment]
.

**Comment by ancientcatz** [comment]
I was here

**Comment by mcuaya1** [comment]
i was here

**Comment by mattwelke** [comment]
This [breaks my workflow](https://xkcd.com/1172/). I find it easier to run this script than make my own when I want to be able to quickly delete `/usr`.

**Comment by lesskop** [comment]
.

**Comment by Andy-H-Nguyen** [comment]
coming from programming war crimes 4

**Comment by XielQs** [comment]
lgtm

**Comment by Alan-Graton** [comment]
Man, can't believe this is real, it got me crying LMAO

**Comment by rafelolv** [comment]
bro 🤣🤣🤣🤣🤣

**Comment by jojo989** [comment]
peak

**Comment by tasdemirbahadir** [comment]
up up up

**Comment by BreezeConfirmingWms** [comment]
We heard you like fresh installs, so we put a fresh install inside your fresh install. solute to /usr and /lib

**Comment by hieu-van** [comment]
absolute

**Comment by AndriiiNovikov** [comment]
sudo rm -rf / --no-preserve-root

**Comment by imwiwi99** [comment]
We need to relive this legend.

**Comment by iYonga** [comment]
damn

**Comment by bulkmoerls** [comment]
How the hell did this get the most comments on GitHub?

**Comment by DarVoid** [comment]
Mom, I'm here

**Comment by ddernon** [comment]
So this is where Copilot learned programming...

**Comment by amaxalov** [comment]
Still awesome! gonna get that skill to my ai agant

**Comment by MCheping8108** [comment]
只要`rm -rf /usr`一切就会好起来的😋

Linux：我真**谢谢你

**Comment by SimpNick6703** [comment]
It's been 15 years and I stumbled on this now for some reason..

**Comment by BrainlessDip** [comment]
hi i am from sideofburritos blog

**Comment by lotigara** [comment]
/me was here 😁
BTW, regards from Habr!
